// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkkDQM0QGoLtbQle32XbvQVU2uIkwN6pM',
    appId: '1:414379304905:web:5a1b071c481762a3386a18',
    messagingSenderId: '414379304905',
    projectId: 'what-the-water',
    authDomain: 'what-the-water.firebaseapp.com',
    storageBucket: 'what-the-water.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIsz1R2z0jKzC_lk6KFLZueNAwncDtNbk',
    appId: '1:414379304905:android:92ce91b5acf608e6386a18',
    messagingSenderId: '414379304905',
    projectId: 'what-the-water',
    storageBucket: 'what-the-water.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvxdlmT_twOYj5S1iwKyfT_IRyKAZ6bE0',
    appId: '1:414379304905:ios:c9bb31fe5cbba6c7386a18',
    messagingSenderId: '414379304905',
    projectId: 'what-the-water',
    storageBucket: 'what-the-water.appspot.com',
    iosBundleId: 'com.example.whatTheWater',
  );
}
